export const REQ_BOXES_DATA_ERROR = '请求分类数据错误'
export const TOKEN_PARAM_REQUIRED = '您的请求未携带token，所以本次请求无效'
export const REQ_DATA_ERROR = '本次请求失败，请稍后重试'
export const TEXT_COPY_SUCCESS = '复制成功'
export const TEXT_COPY_FAIL = '复制失败'
